
SELECT A.*,'||',B.*   
FROM EMPLOYEES A INNER JOIN DEPENDENTS  B 
  ON A.EMPLOYEE_ID = B.EMPLOYEE_ID;

  
SELECT A.EMPLOYEE_ID
       ,A.FIRST_NAME
       ,A.EMAIL
       ,A.SALARY 
       ,B.FIRST_NAME
       ,B.RELATIONSHIP  
FROM EMPLOYEES A INNER JOIN DEPENDENTS  B 
  ON A.EMPLOYEE_ID = B.EMPLOYEE_ID;

  SELECT A.EMPLOYEE_ID
       ,A.FIRST_NAME
       ,A.EMAIL
       ,A.SALARY 
       ,B.FIRST_NAME
       ,B.RELATIONSHIP  
FROM EMPLOYEES A FULL JOIN DEPENDENTS  B 
  ON A.EMPLOYEE_ID = B.EMPLOYEE_ID;
